basefilenames = {'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_04_16\Capture 1_XY1523876898_C0_3',...
    'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_04_16\Capture 2_XY1523877944_C0_2',...
    'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_01_03\Capture 6_XY1514997239_Z0_upper',...
    'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_01_03\Capture 6_XY1514997239_Z0_lower'};
imagefilenames = {'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_04_16\Capture 1_XY1523876898_C0.tiff',...
    'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_04_16\Capture 2_XY1523877944_C0.tiff',...
    'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_01_03\Capture 6_XY1514997239_Z0_T000_C1.tiff',...
    'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_01_03\Capture 6_XY1514997239_Z0_T000_C1.tiff'};
lastMagnetFrame = [34, 41, 48, 48];
%%
basefilenames(1:4) = {'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_08\mix1 sample1\Capture 2_C0',...
    'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_08\mix1 sample1\Capture 4_C0',...
    'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_08\mix1 sample1\Capture 5_C0',...
    'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_08\mix1 sample1\Capture 6_C0'};
imagefilenames(1:4) = cellfun(@(s) [s, '.tiff'], basefilenames(1:4), 'UniformOutput', false);
lastMagnetFrame(1:4) = [37, 45, 31, 43];

basefilenames(5:7) = {'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_08\mix2 sample1\Capture 3_C0',...
...%    'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_08\mix2 sample1\Capture 4_C0',...
    'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_08\mix2 sample1\Capture 5_C0',...
    'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_08\mix2 sample1\Capture 6_C0'};
imagefilenames(5:7) = cellfun(@(s) [s, '.tiff'], basefilenames(5:7), 'UniformOutput', false);
% lastMagnetFrame = [40, 33, 34, 30];
lastMagnetFrame(5:7) = [40, 34, 30];

basefilenames(8:12) = {'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_09\mix1 sample1\Capture 2_C0',...
    'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_09\mix1 sample1\Capture 3_C0',...
    'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_09\mix1 sample1\Capture 4_C0',...
    'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_09\mix1 sample1\Capture 5_C0',...
    'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_09\mix1 sample1\Capture 6_C0'};
imagefilenames(8:12) = cellfun(@(s) [s, '.tiff'], basefilenames(8:12), 'UniformOutput', false);
lastMagnetFrame(8:12) = [37, 43, 38, 35, 24];

basefilenames(13:16) = {'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_09\mix2 sample1\Capture 3_C0',...
    'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_09\mix2 sample1\Capture 4_C0',...
    'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_09\mix2 sample1\Capture 5_C0',...
    'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_09\mix2 sample1\Capture 6_C0'};
imagefilenames(13:16) = cellfun(@(s) [s, '.tiff'], basefilenames(13:16), 'UniformOutput', false);
lastMagnetFrame(13:16) = [37, 44, 50, 29];

basefilenames(17:23) = {'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_09\mix2 sample2\Capture 2_C0_1',...
    'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_09\mix2 sample2\Capture 2_C0_2',...
    'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_09\mix2 sample2\Capture 2_C0_3',...
    'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_09\mix2 sample2\Capture 3_C0',...
    'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_09\mix2 sample2\Capture 4_C0',...
    'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_09\mix2 sample2\Capture 5_C0_2',...
    'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_09\mix2 sample2\Capture 5_C0_3'};
imagefilenames(17:23) = {'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_09\mix2 sample2\Capture 2_C0.tiff',...
    'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_09\mix2 sample2\Capture 2_C0.tiff',...
    'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_09\mix2 sample2\Capture 2_C0.tiff',...
    'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_09\mix2 sample2\Capture 3_C0.tiff',...
    'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_09\mix2 sample2\Capture 4_C0.tiff',...
    'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_09\mix2 sample2\Capture 5_C0.tiff',...
    'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_09\mix2 sample2\Capture 5_C0.tiff'};
lastMagnetFrame(17:23) = [48, 48, 48, 34, 31, 48, 48];

basefilenames(24:31) = {'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_13\mix2 sample1 16_42\Capture 1_C0',...
    'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_13\mix2 sample1 16_42\Capture 2_C0',...
    'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_13\mix2 sample1 16_42\Capture 2_C0_2',...
    'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_13\mix2 sample2 17_05\Capture 1_C0_1',...
    'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_13\mix2 sample2 17_05\Capture 1_C0_2',...
    'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_13\mix2 sample3 17_35\Capture 1_C0',...
    'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_13\mix2 sample4 18_00\Capture 1_C0',...
    'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_13\mix2 sample5 18_32\Capture 1_C0'};
imagefilenames(24:31) = {'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_13\mix2 sample1 16_42\Capture 1_C0.tiff',...
    'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_13\mix2 sample1 16_42\Capture 2_C0.tiff',...
    'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_13\mix2 sample1 16_42\Capture 2_C0.tiff',...
    'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_13\mix2 sample2 17_05\Capture 1_C0.tiff',...
    'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_13\mix2 sample2 17_05\Capture 1_C0.tiff',...
    'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_13\mix2 sample3 17_35\Capture 1_C0.tiff',...
    'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_13\mix2 sample4 18_00\Capture 1_C0.tiff',...
    'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_13\mix2 sample5 18_32\Capture 1_C0.tiff'};
lastMagnetFrame(24:31) = [33, 33, 33, 36, 36, 35, 59, 51];


%% first droplets in samples
basefilenames = {'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_08\mix1 sample1\Capture 2_C0',...
    'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_08\mix2 sample1\Capture 3_C0',...
    'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_09\mix1 sample1\Capture 2_C0',...
    'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_09\mix2 sample1\Capture 3_C0',...
    'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_09\mix2 sample2\Capture 2_C0_1',...
...%     'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_09\mix2 sample2\Capture 2_C0_2',...
...%     'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_09\mix2 sample2\Capture 2_C0_3',...
    'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_13\mix2 sample1 16_42\Capture 1_C0',...
    'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_13\mix2 sample2 17_05\Capture 1_C0_1',...
    'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_13\mix2 sample2 17_05\Capture 1_C0_2',...
    ...%'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_13\mix2 sample3 17_35\Capture 1_C0',...
    'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_13\mix2 sample4 18_00\Capture 1_C0'};%,...
    %'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_13\mix2 sample5 18_32\Capture 1_C0'};

imagefilenames = {'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_08\mix1 sample1\Capture 2_C0.tiff',...
    'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_08\mix2 sample1\Capture 3_C0.tiff',...
    'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_09\mix1 sample1\Capture 2_C0.tiff',...
    'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_09\mix2 sample1\Capture 3_C0.tiff',...
    'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_09\mix2 sample2\Capture 2_C0.tiff',...
...%     'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_09\mix2 sample2\Capture 2_C0.tiff',...
...%     'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_09\mix2 sample2\Capture 2_C0.tiff',...
    'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_13\mix2 sample1 16_42\Capture 1_C0.tiff',...
    'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_13\mix2 sample2 17_05\Capture 1_C0.tiff',...
    'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_13\mix2 sample2 17_05\Capture 1_C0.tiff',...
    ...%'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_13\mix2 sample3 17_35\Capture 1_C0.tiff',...
    'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_13\mix2 sample4 18_00\Capture 1_C0.tiff'};%,...
   % 'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_13\mix2 sample5 18_32\Capture 1_C0.tiff'};
% lastMagnetFrame = [37, 40, 37, 37, 48, 48, 48, 33, 36, 36, 35, 59, 51];
% lastMagnetFrame = [37, 40, 37, 37, 48, 48, 48, 33, 36, 36, 59, 51];
lastMagnetFrame = [37, 40, 37, 37, 48, 33, 36, 36, 59];

%% 60%
basefilenames = {'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_05_14\60% control\mix2 sample1\NCapture 1' ,...
    'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_05_14\60% control\mix2 sample1\NCapture 2' ,...
    ...%'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_05_14\60% control\mix2 sample1\NCapture 5' ,...
     'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_05_14\60% control\mix2 sample1\NCapture 6', ...
     'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_05_14\60% control\mix2 sample2\Capture 1_C0', ...
     'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_05_14\60% control\mix2 sample2\Capture 2_C0', ...
     'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_05_14\60% control\mix2 sample2\Capture 4_C0'};
imagefilenames = {'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_05_14\60% control\mix2 sample1\NCapture 1_T000_C0.tiff' ,...
    'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_05_14\60% control\mix2 sample1\NCapture 2_T000_C1.tiff' ,...
    ...%'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_05_14\60% control\mix2 sample1\NCapture 5_T000_C0.tiff' ,...
    'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_05_14\60% control\mix2 sample1\NCapture 6_T000_C0.tiff', ...
    'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_05_14\60% control\mix2 sample2\Capture 1_C0.tiff', ...
    'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_05_14\60% control\mix2 sample2\Capture 2_C0.tiff', ...
    'Z:\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_05_14\60% control\mix2 sample2\Capture 4_C0.tiff'};
lastMagnetFrame = [43,...
    57,...
    ...%116,...
    38,...
    42,...
    41,...
    40];
%%

clear CCData;
clear drops;
for i = 1:length(basefilenames)
    filename = basefilenames{i};
    dataFilename = [filename,'.mat'];
    data = load(dataFilename);
    drops{i} = data.droplets;
    
% % ----- fix times and save ----- %
%     [~, ~, timeSep] = readCalibration(drops{i}(1).filename);
%     for d=1:numel(drops{i})
%         drops{i}(d).time = (d-1)*timeSep;
%         droplets = drops{i};
%     end
%     save(dataFilename, 'droplets','-v7.3');
% % ------------------------------ %
% % ----- fix calibration and save ----- %
%     for d=1:numel(drops{i})
%         [drops{i}(d).micronsPerPixel] = deal(0.99);
%         droplets = drops{i};
%     end
%     save(dataFilename, 'droplets','-v7.3');
% % ------------------------------------ %
    CCData(i) = smooth_data(drops{i}, -1, 1,[3,35], 1, 7, lastMagnetFrame(i) + 1);
end
for i=1:length(basefilenames)
    if ~isfield(CCData(i), 'lastMagnetFrame') || isempty(CCData(i).lastMagnetFrame)
        CCData(i).lastMagnetFrame = lastMagnetFrame(i);
    end
end
Fig = plot_velocity(CCData,true, true, lastMagnetFrame);
% [~,legendNames,~] = cellfun(@fileparts, basefilenames, 'UniformOutput', false);
% legend(legendNames(1:end), 'interpreter', 'none')
%%
clear CCData_corr
for i = 1:length(CCData)
    MovieFilename = [basefilenames{i},'_with_plots2.avi'];
    images = load_tiff_file(imagefilenames{i},1);
%     [imbalance, corr, lags] = imbalanceVelocityCorrelation(CCData(i), images, lastMagnetFrame(i));
    [CCData_corr(i),  imbalanceFig] = imbalanceVelocityCorrelation(CCData(i), images);
    
% %     KymFig = asymmetryAnalysis(CCData(i), images, lastMagnetFrame(i));
%      drawnow
%     KymFig.PaperPositionMode = 'auto';
%     print(KymFig,[basefilenames{1},' Inetsity Imbalance', '.png'],'-dpng');

    crop = drops{i}(end).dropletPosition + [-10, -10, 20, 20];
    Movie = MakeMovieWithGraphs(images, CCData(i),false, [1 5], crop, 0, true, -1 ,1:lastMagnetFrame(i), {'droplet','time','scale','planes','size', 'aggregate'});
%     Movie = MakeMovieWithGraph3(images, droplets{i}, CCData(i), crop, false, -1 ,1:lastMagnetFrame(i));
    v = VideoWriter(MovieFilename,'Motion JPEG AVI');
    v.FrameRate = 30;
    open(v)
    writeVideo(v,Movie)
    close(v)
end
%% Sample Kymograph - Important: Load first droplets in samples section first

    images = load_tiff_file(imagefilenames{2},1);
    [CCData_corr(2),  imbalanceFig] = imbalanceVelocityCorrelation(CCData(2), images);
    frames = [37,90,255];
    KymFigs = plotCircularKymograph(CCData_corr(2),3, images(frames),frames);
    KymFigs(1).PaperPositionMode = 'auto';
    KymFigs(1).PaperOrientation = 'landscape' ;
    
    print(KymFigs(1),[basefilenames{2},' Kymograph.eps'],'-depsc');
    print(KymFigs(1),[basefilenames{2},' Kymograph.pdf'],'-dpdf');

    for f=2:length(KymFigs)
        KymFigs(f).PaperPositionMode = 'auto';
        print(KymFigs(f),sprintf('%s Kymograph - frame %d.png',basefilenames{2}, f-1),'-dpng');
    end
    imbalanceFig.PaperPositionMode = 'auto';
    imbalanceFig.PaperOrientation = 'landscape' ;
    print(imbalanceFig,sprintf('%s imbalance - velocity correlation.eps',basefilenames{2}),'-depsc');
    print(imbalanceFig,sprintf('%s imbalance - velocity correlation.pdf',basefilenames{2}),'-dpdf');
%% Waves - Load first section (older experiments)
    ind = 4;
    images = load_tiff_file(imagefilenames{ind},1);
    crop = drops{ind}(end).dropletPosition + [-10, -10, 20, 20];
    [CCData_corr,  imbalanceFig] = imbalanceVelocityCorrelation(CCData(ind), images);
    Movie = MakeMovieWithGraphs(images, CCData_corr,false, [1 8 7], crop, 0, true, -1 ,1:lastMagnetFrame(ind), {'droplet','time','scale','planes','size', 'aggregate'});
    MovieFilename = [basefilenames{ind},'_with_plots2.avi'];
    v = VideoWriter(MovieFilename,'Motion JPEG AVI');
    v.FrameRate = 30;
    open(v)
    writeVideo(v,Movie)
    close(v)
    MovieFilename = [basefilenames{ind},'_with_plots2.mp4'];
    v = VideoWriter(MovieFilename,'MPEG-4');
    v.FrameRate = 30;
    open(v)
    writeVideo(v,Movie)
    close(v)

%%
for i=1:3
    Fig(i).PaperPositionMode = 'auto';
%     print(Fig(i),[basefilenames{1},' ',Fig(i).Name,'.eps'],'-depsc');
    print(Fig(i),[basefilenames{1},' ',Fig(i).Name,'.pdf'],'-dpdf');
end