% %% Rambam10 60%
% outputDir = 'C:\Users\Nivieru\Documents\plots\recentering\60%'
% basefilenames = {'W:\phkinnerets\storage\analysis\Niv\rambam10\60%\2019_11_20\capillary\mix1 sample1\Capture 2_C0',...
%     'W:\phkinnerets\storage\analysis\Niv\rambam10\60%\2019_11_20\capillary\mix1 sample1\Capture 3_C0',...
%     'W:\phkinnerets\storage\analysis\Niv\rambam10\60%\2019_11_20\capillary\mix1 sample3\Capture 3_C0_1',...
%     'W:\phkinnerets\storage\analysis\Niv\rambam10\60%\2019_11_20\capillary\mix1 sample3\Capture 3_C0_2',...
% };
% imagefilenames = {'W:\phkinnerets\storage\analysis\Niv\rambam10\60%\2019_11_20\capillary\mix1 sample1\Capture 2_C0.tiff',...
%     'W:\phkinnerets\storage\analysis\Niv\rambam10\60%\2019_11_20\capillary\mix1 sample1\Capture 3_C0.tiff',...
%     'W:\phkinnerets\storage\analysis\Niv\rambam10\60%\2019_11_20\capillary\mix1 sample3\Capture 3_C0.tiff',...
%     'W:\phkinnerets\storage\analysis\Niv\rambam10\60%\2019_11_20\capillary\mix1 sample3\Capture 3_C0.tiff',...
% };
% lastMagnetFrame = [35,32,38,38];
% %% Rambam10 40%
% outputDir = 'C:\Users\Nivieru\Documents\plots\recentering\40%';
% basefilenames = {'W:\phkinnerets\storage\analysis\Niv\rambam10\40%\2019_11_20\capillary\Capture 1_C0',...
%     'W:\phkinnerets\storage\analysis\Niv\rambam10\40%\2019_11_20\capillary\Capture 2_C0_1',...
% ...%     'W:\phkinnerets\storage\analysis\Niv\rambam10\40%\2019_11_20\capillary\Capture 2_C0_2',...
% ...%     'W:\phkinnerets\storage\analysis\Niv\rambam10\40%\2019_11_20\capillary\Capture 3_C0',...
%     'W:\phkinnerets\storage\analysis\Niv\rambam10\40%\2019_12_03\capillary\sample1\Capture 1_C0',...
%     'W:\phkinnerets\storage\analysis\Niv\rambam10\40%\2019_12_03\capillary\sample1\Capture 2_C0',...
%     'W:\phkinnerets\storage\analysis\Niv\rambam10\40%\2019_12_03\capillary\sample2\Capture 1_C0',...
% };
%
% imagefilenames = {'W:\phkinnerets\storage\analysis\Niv\rambam10\40%\2019_11_20\capillary\Capture 1_C0.tiff',...
%     'W:\phkinnerets\storage\analysis\Niv\rambam10\40%\2019_11_20\capillary\Capture 2_C0.tiff',...
% ...%     'W:\phkinnerets\storage\analysis\Niv\rambam10\40%\2019_11_20\capillary\Capture 2_C0.tiff',...
% ...%     'W:\phkinnerets\storage\analysis\Niv\rambam10\40%\2019_11_20\capillary\Capture 3_C0.tiff',...
%     'W:\phkinnerets\storage\analysis\Niv\rambam10\40%\2019_12_03\capillary\sample1\Capture 1_C0.tiff',...
%     'W:\phkinnerets\storage\analysis\Niv\rambam10\40%\2019_12_03\capillary\sample1\Capture 2_C0.tiff',...
%     'W:\phkinnerets\storage\analysis\Niv\rambam10\40%\2019_12_03\capillary\sample2\Capture 1_C0.tiff'...
% };
% % lastMagnetFrame = [11,22,22,39,19,16,10];
% lastMagnetFrame = [11,22,19,16,10];
% Inds = [2,4];
% basefilenames = basefilenames(Inds);
% imagefilenames = imagefilenames(Inds);
% lastMagnetFrame = lastMagnetFrame(Inds);
%
%% Rambam10 80%
cond(1).outputDir = 'C:\Users\Nivieru\Documents\plots\recentering\80%';

cond(1).basefilenames = {'W:\phkinnerets\storage\analysis\Niv\rambam10\2019_11_24\capillary\sample 1\Capture 1_C0',...
    'W:\phkinnerets\storage\analysis\Niv\rambam10\2019_11_24\capillary\sample 1\Capture 2_C0_1_2',...
    'W:\phkinnerets\storage\analysis\Niv\rambam10\2019_11_24\capillary\sample 1\Capture 2_C0_2',...
    'W:\phkinnerets\storage\analysis\Niv\rambam10\2019_11_24\capillary\sample 2\Capture 2_C0',...
    'W:\phkinnerets\storage\analysis\Niv\rambam10\2019_11_24\capillary\sample 2\Capture 3_C0',...
    'W:\phkinnerets\storage\analysis\Niv\rambam10\2019_12_03\capillary\Capture 2_C0_1',...
    'W:\phkinnerets\storage\analysis\Niv\rambam10\2019_12_03\capillary\Capture 2_C0_2'...
    };
cond(1).imagefilenames = {'W:\phkinnerets\storage\analysis\Niv\rambam10\2019_11_24\capillary\sample 1\Capture 1_C0.tiff',...
    'W:\phkinnerets\storage\analysis\Niv\rambam10\2019_11_24\capillary\sample 1\Capture 2_C0.tiff',...
    'W:\phkinnerets\storage\analysis\Niv\rambam10\2019_11_24\capillary\sample 1\Capture 2_C0.tiff',...
    'W:\phkinnerets\storage\analysis\Niv\rambam10\2019_11_24\capillary\sample 2\Capture 2_C0.tiff',...
    'W:\phkinnerets\storage\analysis\Niv\rambam10\2019_11_24\capillary\sample 2\Capture 3_C0.tiff',...
    'W:\phkinnerets\storage\analysis\Niv\rambam10\2019_12_03\capillary\Capture 2_C0.tiff',...
    'W:\phkinnerets\storage\analysis\Niv\rambam10\2019_12_03\capillary\Capture 2_C0.tiff'...
    };
cond(1).lastMagnetFrame = [37, 35, 35, 35, 26, 46, 46];

Inds = [1:2,4:7];
cond(1).basefilenames = cond(1).basefilenames(Inds);
cond(1).imagefilenames = cond(1).imagefilenames(Inds);
cond(1).lastMagnetFrame = cond(1).lastMagnetFrame(Inds);

%% Rambam10 I-phase
cond(2).outputDir = 'C:\Users\Nivieru\Documents\plots\recentering\I-phase';
cond(2).basefilenames = {'W:\phkinnerets\storage\analysis\Niv\rambam10\I-phase\2019_11_20\capillary\mix2 sample1\Capture 2_C0',...
    'W:\phkinnerets\storage\analysis\Niv\rambam10\I-phase\2019_11_20\capillary\mix2 sample2\Capture 1_C0',...
    'W:\phkinnerets\storage\analysis\Niv\rambam10\I-phase\2019_11_28\capillary\mix1 sample1\Capture 1_C0_1',...
    'W:\phkinnerets\storage\analysis\Niv\rambam10\I-phase\2019_11_28\capillary\mix1 sample1\Capture 1_C0_2',...
    'W:\phkinnerets\storage\analysis\Niv\rambam10\I-phase\2019_11_28\capillary\mix1 sample1\Capture 2_C0_1',...
    'W:\phkinnerets\storage\analysis\Niv\rambam10\I-phase\2019_11_28\capillary\mix1 sample1\Capture 2_C0_2',...
    'W:\phkinnerets\storage\analysis\Niv\rambam10\I-phase\2019_11_28\capillary\mix2 sample2\Capture 1_C0',...
    'W:\phkinnerets\storage\analysis\Niv\rambam10\I-phase\2019_12_10\capillary\mix1 sample1\Capture 1_C0',...
    'W:\phkinnerets\storage\analysis\Niv\rambam10\I-phase\2019_12_10\capillary\mix1 sample2\Capture 1_C0',...
    'W:\phkinnerets\storage\analysis\Niv\rambam10\I-phase\2019_12_10\capillary\mix2 sample2\Capture 3_C0',...
    'W:\phkinnerets\storage\analysis\Niv\rambam10\I-phase\2019_12_10\capillary\mix2 sample3\Capture 1_C0',...
    'W:\phkinnerets\storage\analysis\Niv\rambam10\I-phase\2019_12_11\capillary\mix2 sample1\Capture 1_C0',...
    };
cond(2).imagefilenames = {'W:\phkinnerets\storage\analysis\Niv\rambam10\I-phase\2019_11_20\capillary\mix2 sample1\Capture 2_C0.tiff',...
    'W:\phkinnerets\storage\analysis\Niv\rambam10\I-phase\2019_11_20\capillary\mix2 sample2\Capture 1_C0.tiff',...
    'W:\phkinnerets\storage\analysis\Niv\rambam10\I-phase\2019_11_28\capillary\mix1 sample1\Capture 1_C0.tiff',...
    'W:\phkinnerets\storage\analysis\Niv\rambam10\I-phase\2019_11_28\capillary\mix1 sample1\Capture 1_C0.tiff',...
    'W:\phkinnerets\storage\analysis\Niv\rambam10\I-phase\2019_11_28\capillary\mix1 sample1\Capture 2_C0.tiff',...
    'W:\phkinnerets\storage\analysis\Niv\rambam10\I-phase\2019_11_28\capillary\mix1 sample1\Capture 2_C0.tiff',...
    'W:\phkinnerets\storage\analysis\Niv\rambam10\I-phase\2019_11_28\capillary\mix2 sample2\Capture 1_C0.tiff',...
    'W:\phkinnerets\storage\analysis\Niv\rambam10\I-phase\2019_12_10\capillary\mix1 sample1\Capture 1_C0.tiff',...
    'W:\phkinnerets\storage\analysis\Niv\rambam10\I-phase\2019_12_10\capillary\mix1 sample2\Capture 1_C0.tiff',...
    'W:\phkinnerets\storage\analysis\Niv\rambam10\I-phase\2019_12_10\capillary\mix2 sample2\Capture 3_C0.tiff',...
    'W:\phkinnerets\storage\analysis\Niv\rambam10\I-phase\2019_12_10\capillary\mix2 sample3\Capture 1_C0.tiff',...
    'W:\phkinnerets\storage\analysis\Niv\rambam10\I-phase\2019_12_11\capillary\mix2 sample1\Capture 1_C0.tiff',...
    };

cond(2).lastMagnetFrame = [26,32,18,18,18,18,36,65,23,91,61,77];
% Inds = [1,3:7]; % remove 2 because the blob really deforms
Inds = [1,5,6,8,9,10,12]; % Sample times: 20-40 minutes after sample preparaion

cond(2).basefilenames = cond(2).basefilenames(Inds);
cond(2).imagefilenames = cond(2).imagefilenames(Inds);
cond(2).lastMagnetFrame = cond(2).lastMagnetFrame(Inds);

%% Rambam10 + 0.5uM ActA
cond(3).outputDir = 'C:\Users\Nivieru\Documents\plots\recentering\ActA';
cond(3).basefilenames = {'W:\phkinnerets\storage\analysis\Niv\rambam10\ActA\capillary\2019_12_17\mix1 sample1\Capture 2_C0',...
    'W:\phkinnerets\storage\analysis\Niv\rambam10\ActA\capillary\2019_12_17\mix2 sample1\Capture 1_C0',...
    'W:\phkinnerets\storage\analysis\Niv\rambam10\ActA\capillary\2019_12_17\mix2 sample1\Capture 2_C0',...
    'W:\phkinnerets\storage\analysis\Niv\rambam10\ActA\capillary\2019_12_17\mix2 sample2\Capture 2_C0',...
    'W:\phkinnerets\storage\analysis\Niv\rambam10\ActA\capillary\2019_12_19\sample1\Capture 1_C0',...
    'W:\phkinnerets\storage\analysis\Niv\rambam10\ActA\capillary\2019_12_19\sample1\Capture 2_C0',...
    'W:\phkinnerets\storage\analysis\Niv\rambam10\ActA\capillary\2019_12_19\sample1\Capture 3_C0_1',...
    'W:\phkinnerets\storage\analysis\Niv\rambam10\ActA\capillary\2019_12_19\sample2\Capture 1_C0_1',...
    'W:\phkinnerets\storage\analysis\Niv\rambam10\ActA\capillary\2019_12_19\sample2\Capture 1_C0_2',...
    'W:\phkinnerets\storage\analysis\Niv\rambam10\ActA\capillary\2019_12_19\sample2\Capture 1_C0_3',...
    'W:\phkinnerets\storage\analysis\Niv\rambam10\ActA\capillary\2019_12_19\sample2\Capture 2_C0_1',...
    'W:\phkinnerets\storage\analysis\Niv\rambam10\ActA\capillary\2019_12_19\sample2\Capture 2_C0_2',...
    };
cond(3).imagefilenames = {'W:\phkinnerets\storage\analysis\Niv\rambam10\ActA\capillary\2019_12_17\mix1 sample1\Capture 2_C0.tiff',...
    'W:\phkinnerets\storage\analysis\Niv\rambam10\ActA\capillary\2019_12_17\mix2 sample1\Capture 1_C0.tiff',...
    'W:\phkinnerets\storage\analysis\Niv\rambam10\ActA\capillary\2019_12_17\mix2 sample1\Capture 2_C0.tiff',...
    'W:\phkinnerets\storage\analysis\Niv\rambam10\ActA\capillary\2019_12_17\mix2 sample2\Capture 2_C0.tiff',...
    'W:\phkinnerets\storage\analysis\Niv\rambam10\ActA\capillary\2019_12_19\sample1\Capture 1_C0.tiff',...
    'W:\phkinnerets\storage\analysis\Niv\rambam10\ActA\capillary\2019_12_19\sample1\Capture 2_C0.tiff',...
    'W:\phkinnerets\storage\analysis\Niv\rambam10\ActA\capillary\2019_12_19\sample1\Capture 3_C0.tiff',...
    'W:\phkinnerets\storage\analysis\Niv\rambam10\ActA\capillary\2019_12_19\sample2\Capture 1_C0.tiff',...
    'W:\phkinnerets\storage\analysis\Niv\rambam10\ActA\capillary\2019_12_19\sample2\Capture 1_C0.tiff',...
    'W:\phkinnerets\storage\analysis\Niv\rambam10\ActA\capillary\2019_12_19\sample2\Capture 1_C0.tiff',...
    'W:\phkinnerets\storage\analysis\Niv\rambam10\ActA\capillary\2019_12_19\sample2\Capture 2_C0.tiff',...
    'W:\phkinnerets\storage\analysis\Niv\rambam10\ActA\capillary\2019_12_19\sample2\Capture 2_C0.tiff',...
    };

cond(3).lastMagnetFrame = [75, 94, 93, 70, 55, 89, 117, 93, 93, 93, 94, 94];
% Inds = [1,3:7]; % remove 2 because the blob really deforms
Inds = [1:4,6:12];
cond(3).basefilenames = cond(3).basefilenames(Inds);
cond(3).imagefilenames = cond(3).imagefilenames(Inds);
cond(3).lastMagnetFrame = cond(3).lastMagnetFrame(Inds);

%%
removeFields = {'CCData', 'drops', 'lastMagnetFrameAdjusted'};
for fNum = 1:length(removeFields)
    f = removeFields{fNum};
    if isfield(cond, f)
        cond = rmfield(cond,f);
    end
end
for condInd = 1:length(cond)
    cond(condInd).lastMagnetFrame = cond(condInd).lastMagnetFrame + 5;
    for i = 1:length(cond(condInd).basefilenames)
        filename = cond(condInd).basefilenames{i};
        dataFilename = [filename,'.mat'];
        data = load(dataFilename);
        cond(condInd).drops{i} = data.droplets;
        timesep = mean(diff([cond(condInd).drops{i}(2:end).time]));
        cond(condInd).drops{i}(1).time = cond(condInd).drops{i}(2).time - timesep;
        cond(condInd).lastMagnetFrameAdjusted(i) = max(1,cond(condInd).lastMagnetFrame(i) - cond(condInd).drops{i}(1).timepoint); %Fix for series that don't start at first frame
        %     lastMagnetFrameAdjusted(i) = lastMagnetFrame(i);
        cond(condInd).CCData(i) = smooth_data3(cond(condInd).drops{i}, -1, 1,[3,71], 1, 15, cond(condInd).lastMagnetFrameAdjusted(i) + 1);
    end
    for i=1:length(cond(condInd).basefilenames)
        if ~isfield(cond(condInd).CCData(i), 'lastMagnetFrame') || isempty(cond(condInd).CCData(i).lastMagnetFrame)
            cond(condInd).CCData(i).lastMagnetFrame = cond(condInd).lastMagnetFrameAdjusted(i);
        end
    end
%     [Fig, RT, VR, VT, RTmean, VRmean, VTmean] = plot_velocity_paper_nocontinue(cond(condInd).CCData,true, true, cond(condInd).lastMagnetFrameAdjusted, false);
    Fig(:,condInd) = plot_velocity_paper3(cond(condInd).CCData,true, true, cond(condInd).lastMagnetFrame,true, 1, false, 0.9);
%     load('C:\Users\Nivieru\Documents\MATLAB\emulsions_code\plots for paper\from Alex\KerenLab_SimulationResults\Data\fullResults\dynAgg_radDrop=50_pushed_fine.mat')
if condInd == 1
    load('C:\Users\Nivieru\Documents\MATLAB\emulsions_code\plots for paper\from Alex\revision_data_for_Kinneret\data_dynAgg_MvsIphase_vTimePosSpeed.mat');
    vAggPos = vAggPos_all(1,:);
    vAggSpeed = vAggSpeed_all(1,:);
    FigSim(:,condInd) = plot_velocity_paper3(cond(condInd).CCData,true, true, cond(condInd).lastMagnetFrame,false, 2, false, 0.9, vTime, vAggPos, vAggSpeed, -5.5);

elseif condInd == 2
    load('C:\Users\Nivieru\Documents\MATLAB\emulsions_code\plots for paper\from Alex\revision_data_for_Kinneret\data_dynAgg_MvsIphase_vTimePosSpeed_case3_longer.mat');
    FigSim(:,condInd) = plot_velocity_paper3(cond(condInd).CCData,true, true, cond(condInd).lastMagnetFrame,false, 2, false, 0.9, vTime, vAggPos, vAggSpeed, -10);
elseif condInd == 3
     load('C:\Users\Nivieru\Documents\MATLAB\emulsions_code\plots for paper\from Alex\revision_data_for_Kinneret\data_dynAgg_ActA_vTimePosSpeed.mat');
%     load('C:\Users\Nivieru\Documents\MATLAB\emulsions_code\plots for paper\from Alex\revision_data_for_Kinneret\data_dynAgg_ActA_vTimePosSpeed_evenlonger.mat')
    FigSim(:,condInd) = plot_velocity_paper3(cond(condInd).CCData,true, true, cond(condInd).lastMagnetFrame,false, 2, false, 0.9, vTime, vAggPos, vAggSpeed, -20);
end
    
    if exist('format','var') && ischar(format)
        for i=1:length(Fig(:,condInd))
            print('-painters',Fig(i,condInd),fullfile(cond(condInd).outputDir,['magnets_',Fig(i,condInd).Name]),format);
            print('-painters', FigSim(i,condInd),fullfile(cond(condInd).outputDir,['magnets_with_sim',FigSim(i,condInd).Name]),format);
        end
    end
end
%%
% for i = 1:length(cond(condInd).basefilenames)
%     clear CCData_corr
%     for i = 1:length(cond(condInd).CCData)
%         MovieFilename = erase(cond(condInd).basefilenames{i},'W:\phkinnerets\storage\analysis\Niv\rambam10\');
%         MovieFilename = replace(MovieFilename,'\','_');
%         MovieFilename = [MovieFilename,'.avi'];
%         MovieFilename = fullfile('W:\phkinnerets\storage\analysis\Niv\rambam10\movies',MovieFilename);
%         %     loadimages = strrep(imagefilenames{i},'_C0','_C1');
%         loadimages = cond(condInd).imagefilenames{i};
%         %     loadimages = strrep(loadimages,'_C0','_C1');
%         %     MovieFilename = strrep(MovieFilename,'_C0','_C1');
%         greenFlag = false;
%         smoothFlag = true;
%         images = load_tiff_file(loadimages,1);
%         crop = cond(condInd).drops{i}(end).dropletPosition + [-10, -10, 20, 20];
%         %     crop = crop(3:4);
%         Movie{i} = MakeMovieWithGraphs(images, cond(condInd).CCData(i),smoothFlag, [1 5 6], crop, 0, greenFlag, -1 ,1:cond(condInd).lastMagnetFrame(i), {'droplet','time','scale','planes','size', 'aggregate'});
%         %     Movie = MakeMovieWithGraph3(images, droplets{i}, CCData(i), crop, false, -1 ,1:lastMagnetFrame(i));
%         v = VideoWriter(MovieFilename,'Motion JPEG AVI');
%         v.FrameRate = 30;
%         open(v)
%         writeVideo(v,Movie{i})
%         close(v)
%     end
% end