% basefilenames = {'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_04_16\Capture 1_XY1523876898_C0_3',...
%     'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_04_16\Capture 2_XY1523877944_C0_2',...
%     'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_01_03\Capture 6_XY1514997239_Z0_upper',...
%     'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_01_03\Capture 6_XY1514997239_Z0_lower'};
% imagefilenames = {'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_04_16\Capture 1_XY1523876898_C0.tiff',...
%     'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_04_16\Capture 2_XY1523877944_C0.tiff',...
%     'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_01_03\Capture 6_XY1514997239_Z0_T000_C1.tiff',...
%     'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_01_03\Capture 6_XY1514997239_Z0_T000_C1.tiff'};
% lastMagnetFrame = [34, 41, 48, 48];
%%
basefilenames(1:4) = {'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_08\mix1 sample1\Capture 2_C0',...
    'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_08\mix1 sample1\Capture 4_C0',...
    'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_08\mix1 sample1\Capture 5_C0',...
    'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_08\mix1 sample1\Capture 6_C0'};
imagefilenames(1:4) = cellfun(@(s) [s, '.tiff'], basefilenames(1:4), 'UniformOutput', false);
lastMagnetFrame(1:4) = [37, 45, 31, 43];

basefilenames(5:7) = {'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_08\mix2 sample1\Capture 3_C0',...
...%    'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_08\mix2 sample1\Capture 4_C0',...
    'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_08\mix2 sample1\Capture 5_C0',...
    'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_08\mix2 sample1\Capture 6_C0'};
imagefilenames(5:7) = cellfun(@(s) [s, '.tiff'], basefilenames(5:7), 'UniformOutput', false);
% lastMagnetFrame = [40, 33, 34, 30];
lastMagnetFrame(5:7) = [40, 34, 30];

basefilenames(8:12) = {'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_09\mix1 sample1\Capture 2_C0',...
    'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_09\mix1 sample1\Capture 3_C0',...
    'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_09\mix1 sample1\Capture 4_C0',...
    'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_09\mix1 sample1\Capture 5_C0',...
    'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_09\mix1 sample1\Capture 6_C0'};
imagefilenames(8:12) = cellfun(@(s) [s, '.tiff'], basefilenames(8:12), 'UniformOutput', false);
lastMagnetFrame(8:12) = [37, 43, 38, 35, 24];

basefilenames(13:16) = {'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_09\mix2 sample1\Capture 3_C0',...
    'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_09\mix2 sample1\Capture 4_C0',...
    'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_09\mix2 sample1\Capture 5_C0',...
    'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_09\mix2 sample1\Capture 6_C0'};
imagefilenames(13:16) = cellfun(@(s) [s, '.tiff'], basefilenames(13:16), 'UniformOutput', false);
lastMagnetFrame(13:16) = [37, 44, 50, 29];

basefilenames(17:23) = {'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_09\mix2 sample2\Capture 2_C0_1',...
    'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_09\mix2 sample2\Capture 2_C0_2',...
    'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_09\mix2 sample2\Capture 2_C0_3',...
    'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_09\mix2 sample2\Capture 3_C0',...
    'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_09\mix2 sample2\Capture 4_C0',...
    'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_09\mix2 sample2\Capture 5_C0_2',...
    'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_09\mix2 sample2\Capture 5_C0_3'};
imagefilenames(17:23) = {'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_09\mix2 sample2\Capture 2_C0.tiff',...
    'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_09\mix2 sample2\Capture 2_C0.tiff',...
    'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_09\mix2 sample2\Capture 2_C0.tiff',...
    'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_09\mix2 sample2\Capture 3_C0.tiff',...
    'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_09\mix2 sample2\Capture 4_C0.tiff',...
    'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_09\mix2 sample2\Capture 5_C0.tiff',...
    'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_09\mix2 sample2\Capture 5_C0.tiff'};
lastMagnetFrame(17:23) = [48, 48, 48, 34, 31, 48, 48];

basefilenames(24:31) = {'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_13\mix2 sample1 16_42\Capture 1_C0',...
    'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_13\mix2 sample1 16_42\Capture 2_C0',...
    'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_13\mix2 sample1 16_42\Capture 2_C0_2',...
    'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_13\mix2 sample2 17_05\Capture 1_C0_1',...
    'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_13\mix2 sample2 17_05\Capture 1_C0_2',...
    'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_13\mix2 sample3 17_35\Capture 1_C0',...
    'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_13\mix2 sample4 18_00\Capture 1_C0',...
    'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_13\mix2 sample5 18_32\Capture 1_C0'};
imagefilenames(24:31) = {'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_13\mix2 sample1 16_42\Capture 1_C0.tiff',...
    'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_13\mix2 sample1 16_42\Capture 2_C0.tiff',...
    'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_13\mix2 sample1 16_42\Capture 2_C0.tiff',...
    'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_13\mix2 sample2 17_05\Capture 1_C0.tiff',...
    'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_13\mix2 sample2 17_05\Capture 1_C0.tiff',...
    'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_13\mix2 sample3 17_35\Capture 1_C0.tiff',...
    'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_13\mix2 sample4 18_00\Capture 1_C0.tiff',...
    'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_13\mix2 sample5 18_32\Capture 1_C0.tiff'};
lastMagnetFrame(24:31) = [33, 33, 33, 36, 36, 35, 59, 51];

% Inds = [1,5:9,13:17,20:28,30];
Inds = [1,5:6,8:9,13:19,23:25,27:28,30:31];

IndsInv = 1:31;
IndsInv(Inds) = [];
% Inds = [18,19,31];
% Inds = [1,5:9,12:17,20:23,25:26];
basefilenames = basefilenames(Inds);
imagefilenames = imagefilenames(Inds);
lastMagnetFrame = lastMagnetFrame(Inds);


% %% first droplets in samples
% basefilenames = {'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_08\mix1 sample1\Capture 2_C0',...
%     'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_08\mix2 sample1\Capture 3_C0',...
%     'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_09\mix1 sample1\Capture 2_C0',...
%     'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_09\mix2 sample1\Capture 3_C0',...
%     'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_09\mix2 sample2\Capture 2_C0_1',...
% ...%     'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_09\mix2 sample2\Capture 2_C0_2',...
% ...%     'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_09\mix2 sample2\Capture 2_C0_3',...
%     'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_13\mix2 sample1 16_42\Capture 1_C0',...
%     'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_13\mix2 sample2 17_05\Capture 1_C0_1',...
%     'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_13\mix2 sample2 17_05\Capture 1_C0_2',...
%     ...%'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_13\mix2 sample3 17_35\Capture 1_C0',...
%     'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_13\mix2 sample4 18_00\Capture 1_C0'};%,...
%     %'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_13\mix2 sample5 18_32\Capture 1_C0'};
% 
% imagefilenames = {'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_08\mix1 sample1\Capture 2_C0.tiff',...
%     'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_08\mix2 sample1\Capture 3_C0.tiff',...
%     'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_09\mix1 sample1\Capture 2_C0.tiff',...
%     'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_09\mix2 sample1\Capture 3_C0.tiff',...
%     'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_09\mix2 sample2\Capture 2_C0.tiff',...
% ...%     'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_09\mix2 sample2\Capture 2_C0.tiff',...
% ...%     'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_09\mix2 sample2\Capture 2_C0.tiff',...
%     'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_13\mix2 sample1 16_42\Capture 1_C0.tiff',...
%     'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_13\mix2 sample2 17_05\Capture 1_C0.tiff',...
%     'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_13\mix2 sample2 17_05\Capture 1_C0.tiff',...
%     ...%'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_13\mix2 sample3 17_35\Capture 1_C0.tiff',...
%     'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_13\mix2 sample4 18_00\Capture 1_C0.tiff'};%,...
%    % 'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_08_13\mix2 sample5 18_32\Capture 1_C0.tiff'};
% % lastMagnetFrame = [37, 40, 37, 37, 48, 48, 48, 33, 36, 36, 35, 59, 51];
% % lastMagnetFrame = [37, 40, 37, 37, 48, 48, 48, 33, 36, 36, 59, 51];
% lastMagnetFrame = [37, 40, 37, 37, 48, 33, 36, 36, 59];

% %% 60%
% basefilenames = {'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_05_14\60% control\mix2 sample1\NCapture 1' ,...
%     'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_05_14\60% control\mix2 sample1\NCapture 2' ,...
%     ...%'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_05_14\60% control\mix2 sample1\NCapture 5' ,...
%      'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_05_14\60% control\mix2 sample1\NCapture 6', ...
%      'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_05_14\60% control\mix2 sample2\Capture 1_C0', ...
%      'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_05_14\60% control\mix2 sample2\Capture 2_C0', ...
%      'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_05_14\60% control\mix2 sample2\Capture 4_C0'};
% imagefilenames = {'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_05_14\60% control\mix2 sample1\NCapture 1_T000_C0.tiff' ,...
%     'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_05_14\60% control\mix2 sample1\NCapture 2_T000_C1.tiff' ,...
%     ...%'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_05_14\60% control\mix2 sample1\NCapture 5_T000_C0.tiff' ,...
%     'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_05_14\60% control\mix2 sample1\NCapture 6_T000_C0.tiff', ...
%     'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_05_14\60% control\mix2 sample2\Capture 1_C0.tiff', ...
%     'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_05_14\60% control\mix2 sample2\Capture 2_C0.tiff', ...
%     'W:\phkinnerets\storage\analysis\Niv\magnetic beads\magnetic beads in capillary\spinning disk\2018_05_14\60% control\mix2 sample2\Capture 4_C0.tiff'};
% lastMagnetFrame = [43,...
%     57,...
%     ...%116,...
%     38,...
%     42,...
%     41,...
%     40];
%%

clear CCData;
clear drops;
for i = 1:length(basefilenames)
    filename = basefilenames{i};
    dataFilename = [filename,'.mat'];
    data = load(dataFilename);
    drops{i} = data.droplets;
    timesep = mean(diff([drops{i}(2:end).time]));
    drops{i}(1).time = drops{i}(2).time - timesep;
    lastMagnetFrameAdjusted(i) = max(1,lastMagnetFrame(i) - drops{i}(1).timepoint); %Fix for series that don't start at first frame

% % ----- fix times and save ----- %
%     [~, ~, timeSep] = readCalibration(drops{i}(1).filename);
%     for d=1:numel(drops{i})
%         drops{i}(d).time = (d-1)*timeSep;
%         droplets = drops{i};
%     end
%     save(dataFilename, 'droplets','-v7.3');
% % ------------------------------ %
% % ----- fix calibration and save ----- %
%     for d=1:numel(drops{i})
%         [drops{i}(d).micronsPerPixel] = deal(0.99);
%         droplets = drops{i};
%     end
%     save(dataFilename, 'droplets','-v7.3');
% % ------------------------------------ %
%     CCData(i) = smooth_data3(drops{i}, -1, 1,[3,35], 1, 7, lastMagnetFrame(i) + 1);
    CCData(i) = smooth_data3(drops{i}, -1, 1,[3,71], 1, 15, lastMagnetFrameAdjusted(i) + 1);
end
for i=1:length(basefilenames)
    if ~isfield(CCData(i), 'lastMagnetFrame') || isempty(CCData(i).lastMagnetFrame)
        CCData(i).lastMagnetFrame = lastMagnetFrame(i);
    end
end
oneDropInd = 2;
% [Fig, RT, VR, VT, RTmean, VRmean, VTmean] = plot_velocity_paper(CCData,true, true, lastMagnetFrame, false);
Fig = plot_velocity_paper3(CCData,true, true, lastMagnetFrame,true, 2, false, 0.9);
for f = 1:length(Fig)
    for ln=3:numel(Fig(f).Children(1).Children)
        Fig(f).Children(1).Children(ln).Color(4) = 0.3;
    end
end
% load('C:\Users\Nivieru\Documents\MATLAB\emulsions_code\plots for paper\from Alex\KerenLab_SimulationResults\Data\dynAgg_varyRad_timePosSpeed');
% FigSim = plot_velocity_paper_with_sim(CCData,true, true, lastMagnetFrame, aTime, aAggPos(:,4), aAggSpeed(:,4), -5.5);
load('C:\Users\Nivieru\Documents\MATLAB\emulsions_code\plots for paper\from Alex\KerenLab_SimulationResults\Data\fullResults\dynAgg_radDrop=50_pushed_fine.mat')
% FigSim = plot_velocity_paper_with_sim(CCData,true, true, lastMagnetFrame, vTime, vAggPos, vAggSpeed, -5.5);
FigSim = plot_velocity_paper3(CCData,true, true, lastMagnetFrame,false, 2, false, 0.9, vTime, vAggPos, vAggSpeed, -5.5);
FigOneDrop = plot_velocity_paper2(CCData(oneDropInd),true, true, lastMagnetFrame(oneDropInd), true);
BFImagefilename = strrep(imagefilenames{oneDropInd}, 'C0', 'C1');
% FigOneDropImage = imageTrack_paper(CCData(oneDropInd),BFImagefilename, lastMagnetFrame(oneDropInd));

if exist('format','var') && ischar(format) && exist('outputDir', 'var') && ischar(outputDir)
    for i=1:length(Fig)
        print('-painters',Fig(i),fullfile(outputDir,['magnets_',Fig(i).Name]),format);
        print('-painters', FigSim(i),fullfile(outputDir,['magnets_with_sim',FigSim(i).Name]),format);
    end
    print('-painters',FigOneDrop(1),fullfile(outputDir,['magnets_oneDrop_',FigOneDrop(1).Name]),format);
%     print(FigOneDropImage,fullfile(outputDir,'magnets_oneDrop_image'),'-depsc', '-opengl');
end


% [~,legendNames,~] = cellfun(@fileparts, basefilenames, 'UniformOutput', false);
% legend(legendNames(1:end), 'interpreter', 'none')
%%
plot_mean_recenteringV(CCData, true, true, lastMagnetFrame);
%%
% clear CCData_corr
% for i = 1:length(CCData)
%     MovieFilename = [basefilenames{i},'_with_plots2.avi'];
%     images = load_tiff_file(imagefilenames{i},1);
% %     [imbalance, corr, lags] = imbalanceVelocityCorrelation(CCData(i), images, lastMagnetFrame(i));
%     [CCData_corr(i),  imbalanceFig] = imbalanceVelocityCorrelation(CCData(i), images);
%     
% % %     KymFig = asymmetryAnalysis(CCData(i), images, lastMagnetFrame(i));
% %      drawnow
% %     KymFig.PaperPositionMode = 'auto';
% %     print(KymFig,[basefilenames{1},' Inetsity Imbalance', '.png'],'-dpng');
% 
%     crop = drops{i}(end).dropletPosition + [-10, -10, 20, 20];
%     Movie = MakeMovieWithGraphs(images, CCData(i),false, [1 5], crop, 0, true, -1 ,1:lastMagnetFrame(i), {'droplet','time','scale','planes','size', 'aggregate'});
% %     Movie = MakeMovieWithGraph3(images, droplets{i}, CCData(i), crop, false, -1 ,1:lastMagnetFrame(i));
%     v = VideoWriter(MovieFilename,'Motion JPEG AVI');
%     v.FrameRate = 30;
%     open(v)
%     writeVideo(v,Movie)
%     close(v)
% end
%% Sample Kymograph - Important: Load first droplets in samples section first
    mov = 2;
    images = load_tiff_file(imagefilenames{mov},1);
    [CCData_corr(mov),  imbalanceFig] = imbalanceVelocityCorrelation_paper(CCData(mov), images);
%     frames = [37,90,255];
    frames = [39, 100, length(images)-10];
    background_substraction = 1.2e4;
    KymFigs = plotCircularKymograph_paper(CCData_corr(mov),3, images(frames),frames, background_substraction);
    KymFigs(1).Children(1).XLim = [0,10];
    KymFigs(1).PaperPositionMode = 'auto';
    KymFigs(1).PaperOrientation = 'landscape' ;
    
%     print(KymFigs(1),[basefilenames{2},' Kymograph.eps'],'-depsc');
if exist('format','var') && ischar(format) && exist('outputDir', 'var') && ischar(outputDir)
    print(KymFigs(1),fullfile(outputDir,'magnets_Kymograph'),format);
end
if exist('format','var') && ischar(format) && exist('outputDir', 'var') && ischar(outputDir)
    for f=2:length(KymFigs)
        KymFigs(f).PaperPositionMode = 'auto';
        print(KymFigs(f),fullfile(outputDir,sprintf('magnets_Kymograph - frame %d', f-1)),format);
    end
    imbalanceFig.PaperPositionMode = 'auto';
    imbalanceFig.PaperOrientation = 'landscape' ;
%     print(imbalanceFig,fullfile('plots for paper','imbalance - velocity correlation.eps'),'-depsc');
    print(imbalanceFig,fullfile(outputDir,'magnets_imbalance - velocity correlation'),format);
end
%% Waves - Load first section (older experiments)
%     ind = 4;
%     images = load_tiff_file(imagefilenames{ind},1);
%     crop = drops{ind}(end).dropletPosition + [-10, -10, 20, 20];
%     [CCData_corr,  imbalanceFig] = imbalanceVelocityCorrelation(CCData(ind), images);
%     Movie = MakeMovieWithGraphs(images, CCData_corr,false, [1 8 7], crop, 0, true, -1 ,1:lastMagnetFrame(ind), {'droplet','time','scale','planes','size', 'aggregate'});
%     MovieFilename = [basefilenames{ind},'_with_plots2.avi'];
%     v = VideoWriter(MovieFilename,'Motion JPEG AVI');
%     v.FrameRate = 30;
%     open(v)
%     writeVideo(v,Movie)
%     close(v)
%     MovieFilename = [basefilenames{ind},'_with_plots2.mp4'];
%     v = VideoWriter(MovieFilename,'MPEG-4');
%     v.FrameRate = 30;
%     open(v)
%     writeVideo(v,Movie)
%     close(v)

%%
% for i=1:3
%     Fig(i).PaperPositionMode = 'auto';
%     print(Fig(i),[basefilenames{1},' ',Fig(i).Name,'.eps'],'-depsc');
%     print(Fig(i),[basefilenames{1},' ',Fig(i).Name,'.pdf'],'-dpdf');
% end